### ISSUE TITLE
Allow giants to be configured and set as aggressive

### ISSUE THREAD

**Issue by WyndevCodes** [SlimeDog/AggressiveAnimals#59]
**Describe the solution you'd like:**
I would like giants (the massive zombies) to be able to be set as aggressive. The previous version (<1.17) of AggressiveAnimals had this option in the configuration, and it is very useful.

**Comment by SlimeDog** [comment]
Good idea. We'll have a look.

**Comment by SlimeDog** [comment]
What plugin are you using to give giants AI (vanilla giants have no AI)?

**Comment by WyndevCodes** [comment]
From what I understand, the previous version of AggressiveAnimals uses NMS to wipe the old AI of the mobs and add new AI to make them aggressive. For the giant, I've used AI with NMS before and know it is possible to add goal selectors and target selectors and make it attack, but that was in 1.17. I'm currently using your plugin to avoid using NMS in my own plugin, so if it's not possible in the newest version let me know.

**Comment by WyndevCodes** [comment]
So my though process is that you can just add AI to the giant and it should become aggressive.

**Comment by SlimeDog** [comment]
> From what I understand, the previous version of AggressiveAnimals uses NMS to wipe the old AI of the mobs and add new AI to make them aggressive.

Unfortunately, we cannot look at the former-guy's code to know what he did.

My understanding is that we do not "add AI" to the passive and neutral mob-types; we just manipulate the existing AI tags (you could review the [source code](https://github.com/SlimeDog/AggressiveAnimals/) to see what we do). Since vanilla giants do not have AI, I'm not sure how we proceed. But Mart will know ...

**Comment by WyndevCodes** [comment]
Yeah, makes sense. I thought that as long as the mob has the method to set a target and goal selector (which I'm pretty sure the NMS giant has) it should work, but that was a few versions ago. I look forward to hearing Mart's response!

**Comment by SlimeDog** [comment]
Quick note: Mart is over-engaged IRL, so cannot spend time on this issue at the moment. He or I will post when we actually start to dive in.

**Comment by mart-r** [comment]
Sorry for the late reply. As noted by SlimeDog, I was rather busy.

But in the way we're currently doing this, we are sort of adding (very basic!) attack AI to mobs. As such, adding a GIANT seems trivial.
With that said, I wouldn't guarantee this works alongside other plugins that change the giant's AI.

In any case, PR upcoming soon and subsequently the update as well, hopefully.

**Comment by WyndevCodes** [comment]
Awesome! I can't wait!

**Comment by SlimeDog** [comment]
I tested on
Paper 1.20.1-159
BetterGiants 2.8 (old, may not work correctly with MC 1.20.1, but no errors generated)
AggressiveAnimals 1.5.3-SNAPSHOT
```
mobs:
  giant:
    enabled: true
    always-aggressive: true
```
The giant didn't find me until I attacked it, but that may be due to deficiencies in the BetterGiants AI. Once attacked, it stayed after me, as it should. So it seems to be working.

**Comment by SlimeDog** [comment]
AA 1.6.0 published on Hangar, Modrinth, and SpigotMC.
